---
overrides:
  - files: ["*.js"]
    options:
      semi: false
      singleQuote: true
  # Use single quotes in GitHub workflow files
  - files: ".github/workflows/*.(yml|yaml)"
    options:
      singleQuote: true
