---
name: 'Suggest Changes'
description: 'Create review suggestions from working directory changes'
inputs:
  github-token:
    description: github token
    default: ${{ github.token }}
  comment:
    description: The pull request review comment
runs:
  using: 'node20'
  main: 'dist/index.js'
